### ISSUE TITLE
Aliased classes in return statements are not mantained when ported to PHP7

### ISSUE THREAD

**Issue by nilportugues** [dunglas/phpdoc-to-typehint#15]
Problem is, it will resolve the original class and write the FQN instead of keeping the Alias. 

This leads to namespace collisions.

**Comment by dunglas** [comment]
Thanks for the report @nilportugues. Do you have some time to work on a patch?

**Comment by nilportugues** [comment]
Not really but I can try.

 I've checked your code... 
https://github.com/dunglas/phpdoc-to-typehint/blob/master/src/Converter.php#L369 seems to be there where the patch must be applied.

I'd check also if this happens for all aliased classes. I suspect it's the case.
