### ISSUE TITLE
Support PHP7.1

### ISSUE THREAD

**Issue by zalsader** [dunglas/phpdoc-to-typehint#16]
Hello,

Are there any plans to support [PHP7.1](http://php.net/manual/en/migration71.new-features.php) new type declarations and nullable types? Example:

```php
function returnsNothing(iterable $iterable, ?string $nullableString): void {
...
}
```

**Comment by dunglas** [comment]
Hi,

There is nothing started yet but a PR is welcome!

**Comment by zalsader** [comment]
I'll see if I could do anything, Thanks.

**Comment by ricordisamoa** [comment]
#25 adds nullable types behind a command-line flag

**Comment by hkdobrev** [comment]
So the only thing missing from PHP 7.1 support is the void return type declaration?
