### ISSUE TITLE
Cannot ue 'Void' as class name

### ISSUE THREAD

**Issue by staabm** [dunglas/phpdoc-to-typehint#28]
using the latest release v.0.1.0 I am running into the following error

```
$ php phpdoc-to-typehint.phar .
PHP Fatal error:  Cannot use 'Void' as class name as it is reserved in phar://C:
/Users/mstaab/Documents/GitHub/deployer/phpdoc-to-typehint.phar/vendor/phpdocume
ntor/type-resolver/src/Types/Void.php on line 23

Fatal error: Cannot use 'Void' as class name as it is reserved in phar://C:/User
s/mstaab/Documents/GitHub/deployer/phpdoc-to-typehint.phar/vendor/phpdocumentor/
type-resolver/src/Types/Void.php on line 23
```

seems like the downloaded phar is unusable to run on php7.1+

```
$ php -v
PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:45) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by lyrixx** [comment]
Same issue here

**Comment by elliotchance** [comment]
Yes, I am also getting this. There isn't enough context in the error to pinpoint the code that is triggering it.

**Comment by DIDoS** [comment]
Same here

**Comment by dunglas** [comment]
PHP 7.1+ isn't supported yet. Patches are very welcome (see #29) :)

**Comment by ADmad** [comment]
> PHP 7.1+ isn't supported yet. Patches are very welcome (see #29) :)

Please at least update the readme for now stating this fact :slightly_smiling_face:.

**Comment by lyrixx** [comment]
@ADmad would you mind subit a pr ?

**Comment by TomasVotruba** [comment]
This might help: https://github.com/rectorphp/rector/pull/795

It's also support PHP 7.2+
