### ISSUE TITLE
@see is mistaken for a type

### ISSUE THREAD

**Issue by elliotchance** [dunglas/phpdoc-to-typehint#30]
The following class instance variable:

```php
    /**
     * If you’ve enabled user specific timezones, you may set or update the
     * user timezone.
     * @see https://docs.looker.com/reference/embedding/timezones
     * @var string|null
     */
    public $userTimeZone = null;
```

Produces the error:

```
  [InvalidArgumentException]
  "\Kounta\Insights\Looker\https://docs.looker.com/reference/embedding/timezones" is not a valid Fqsen.
```

**Comment by TomasVotruba** [comment]
This error is very common among other tags as well, due to https://github.com/phpDocumentor/ReflectionDocBlock
You'd have to create own tags with fixes: https://github.com/Symplify/Symplify/blob/f80fada524b7a198782a07836ce20ee13b457900/packages/BetterReflectionDocBlock/src/CleanDocBlockFactory.php#L28

or use more advanced phpdoc-parser: https://github.com/phpstan/phpdoc-parser, that is used also by PHPStan

I tried them both and I must say the later wins :champagne:

**Comment by TomasVotruba** [comment]
Few months in the future... :) there is PR in Rector that supports and a solves that:
https://github.com/rectorphp/rector/pull/795

**Comment by dunglas** [comment]
@TomasVotruba do you think we can deprecate this package in favor of Rector?

**Comment by TomasVotruba** [comment]
I think so :+1:  I've already ported tests from here, from nikic/TypeUtil and from php-cs-fixer today

I plan to add few more tests, than try it on Symfony code and see what happens :) that should be "battle-tested"

**Comment by dunglas** [comment]
Ok, let me know when you think that there is a feature parity and that the project is stable enough. I'll then archive this repo and redirect to Rector.

**Comment by TomasVotruba** [comment]
Will do, thanks for being open to this :+1:

**Comment by dunglas** [comment]
You're very welcome, I've not the time to actively work on this project anymore, and Rector looks very promising.

**Comment by TomasVotruba** [comment]
I've tested it on Symfony and released after many bugfixes in Rector [v0.3.22](https://github.com/rectorphp/rector/releases/tag/v0.3.22).

Apart classic docblock → typehint it includes:

- skip for override of `vendor` method without typehint
- propagation of added typehint on all children - classes and interfaces
- propagation of added typehint on class that implements interface and that required a method, that is used from a trait
- PHP 7.1 and nullables by default
- PHP 7.2 and `object` typehint enabled by parameter

### Install

```
composer require rector/rector --dev
```

### Setup

```yaml
# rector.yml
services:
    Rector\Php\Rector\FunctionLike\ParamScalarTypehintRector: ~
    Rector\Php\Rector\FunctionLike\ReturnScalarTypehintRector: ~
```

### Run

```
vendor/bin/rector process src --dry-run
```

```
vendor/bin/rector process src
```

**Comment by TomasVotruba** [comment]
It's out: https://www.tomasvotruba.cz/blog/2018/12/10/rocket-science-behind-migration-of-docblock-types-to-php-typehints/

**Comment by TomasVotruba** [comment]
> Ok, let me know when you think that there is a feature parity and that the project is stable enough. I'll then archive this repo and redirect to Rector.

Btw, this si done since my last comment. Already tagged and used by people, so you you can archive and recommend Rector :bowing_man:
