### ISSUE TITLE
Nullable type hints in existing code break the parser

### ISSUE THREAD

**Issue by hkdobrev** [dunglas/phpdoc-to-typehint#32]
Signatures like these below break the parser:

```php
function(?Foo $foo) {}
```

```php
function(): ?Foo {}
```

**Comment by dereuromark** [comment]
Sounds related to https://github.com/dunglas/phpdoc-to-typehint/issues/16 and the PR https://github.com/dunglas/phpdoc-to-typehint/pull/29
