### ISSUE TITLE
RFC: Do not change method signature when this would break inheritance

### ISSUE THREAD

**Issue by hkdobrev** [dunglas/phpdoc-to-typehint#33]
If the function is overriding a parent method there are limitations to changing the method signature. Future PHP versions could improve that with more support for [Covariance and Contravariance](https://en.m.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)), but there are still cases where signatures could not blindly be changed.

If the PHPDoc to typehints conversion take this into account and don't change things which would produce a direct PHP error it would be less risky and could be deployed more widely. It could even work in a CI environment.

**Comment by TomasVotruba** [comment]
PHP Tokens can't really handle this.

This is the main point of AST ingreation. I'm working on it here: https://github.com/rectorphp/rector/pull/795

Any feedback is appreciated :+1:
