### ISSUE TITLE
InvalidArgumentException at @see

### ISSUE THREAD

**Issue by kfreiman** [dunglas/phpdoc-to-typehint#6]
``` php
/**
* @see http://swiftmailer.org
*/
```

throws 

``` sh
  [InvalidArgumentException]                                       
  "\yii\swiftmailer\http://swiftmailer.org" is not a valid Fqsen.                                                                   

```

**Comment by meyerbaptiste** [comment]
This comes from phpDocumentor, IMO it is not our responsibility.

[`@see only displays links to element documentation. If you want to display a hyperlink, use @link or inline {@link}`](http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.see.pkg.html)
